// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"NpcNames","status":true,"description":"แสดงชื่อ NPC บนหัวตัวละครโดยอ่านจาก Note tag","parameters":{}},
{"name":"EnemyHPGauge","status":true,"description":"แสดงหลอด HP สีแดงเหนือหัวศัตรูในฉากต่อสู้","parameters":{}},
{"name":"WASDMovement","status":true,"description":"Enables WASD keys for player movement and menu navigation.","parameters":{"disableArrows":"false"}},
{"name":"MobileControls","status":true,"description":"Adds on-screen touch controls (D-Pad and Buttons) for mobile devices.","parameters":{"showOnPC":"true","opacity":"150","padScale":"1.0"}},
{"name":"JustGuard","status":true,"description":"[v9.1 Fixed] Just Guard: Fixed 0 Dmg & Tuned Speed (x1.2 Slower)","parameters":{"--- Game Settings ---":"","StunStateId":"13","MinDuration":"1","MaxDuration":"30","--- Visual Button ---":"","PromptX":"640","PromptY":"300","--- Audio & FX ---":"","ParrySound":"Sword2\r\n*","FailSound":"Buzzer1"}},
{"name":"SurvivalInstinct","status":true,"description":"[v1.0] ระบบ Guts (รอดตาย) และ Life Steal (ฟื้นเลือดเมื่อฆ่า)","parameters":{"--- Guts Settings ---":"","EnableGuts":"true","GutsSound":"Powerup","--- Life Steal Settings ---":"","EnableLifeSteal":"true","HealPercent":"10","HealSound":"Heal3"}},
{"name":"DeckBattleSystem","status":true,"description":"v2.1 Deckbuilder System: Bug Fixes & Deck Editor.","parameters":{"Hand Size":"5","Keep Hand":"false","Excluded Skills":"[\"2\"]","--- Deck Mechanics ---\n*":"","Min Deck Size":"4","Max Deck Size":"30","--- MP Mechanics ---":"","MP Regen Amount":"35","--- Controls ---\n*":"","Discard Key":"c","--- Draw Mechanic ---\n*":"","Show Draw Command":"true\n*","Draw Command Name":"Draw (+1)\n*","Draw MP Cost":"0\n*","Draw TP Cost":"0","--- Skip Mechanic ---\n*":"","Show Skip Command":"true\n*","Skip Command Name":"Skip Turn","--- HUD Settings ---":"","Deck Window X":"right","Deck Window Y":"0","Show HUD Background":"true","--- Menu Settings ---":"","Show Deck Menu":"true\n*","Deck Menu Name":"Deck"}}
];
